### ISSUE TITLE
Implement server-side zone time tracking

### ISSUE THREAD

**Issue by sashforth** [WildPetScience/Condor#30]
This has now been removed from the client-side analysis stage - it needs to be done on the server.

Please bear in mind that the previous implementation tracked the # of visits - this is actually incorrect and the new implementation should track total time (using timestamps) that the animal is in each zone.

The null Zone (with id = "N/A") is _always_ part of the Zone Set.

I (@sashforth) might try to do this once/if I figure out how the server-side is structured.

**Comment by w-shackleton** [comment]
Heh
